# Generated by Django 6.0.4 on 2026-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_resume_alter_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
