# Generated by Django 6.0.4 on 2026-05-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_github_username_profile_linkedin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_username',
        ),
    ]
