# Generated by Django 6.0.4 on 2026-05-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='keypoint',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='keypoint',
        ),
        migrations.RemoveField(
            model_name='education',
            name='keypoint',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='keypoint',
        ),
        migrations.RemoveField(
            model_name='project',
            name='keypoint',
        ),
    ]
