# Generated by Django 6.0.4 on 2026-05-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_achievement_keypoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
    ]
