# Generated by Django 6.0.4 on 2026-05-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_education_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
