# Generated by Django 6.0.4 on 2026-05-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_tech_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill_name',
            old_name='skill_Name',
            new_name='skill_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_name',
        ),
    ]
